### PR TITLE
Revert "falcon: Fix reverse stereo on speakers/earphones"

### PR DESCRIPTION
**Pull request by ShiroiKarasu6991**
The previous fix was just temporary; a soft reboot causes the problem to occur again until a hard reboot is done. (adjusments have to be made in the audio HAL itself?)

### CODE REVIEW

**Comment by luk1337** [comment]
You need to submit it to gerrit.

**Comment by ShiroiKarasu6991** [comment]
Could you please submit this patch for me, please? I'm having trouble setting things up here.

**Comment by luk1337** [comment]
it isn't that hard lel.

**Comment by luk1337** [comment]
I can try to help you with gerrit. get on freenode IRC, my nickname LuK1337

**Pull request closed without merging**
